language: java
script: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB-TOKEN # github 上的token环境变量
  local-dir: ./_book/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
 
